"""Add x and y coordinates to Task model

Revision ID: 2275278af853
Revises: 
Create Date: 2025-05-28 17:50:08.055006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2275278af853'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('y', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('y')
        batch_op.drop_column('x')

    # ### end Alembic commands ###
